---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: pacman-ansible-demo
  name: pacman-ansible-demo-placement-0
  namespace: pacman
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
