---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: nginx-placement
      namespace: nginx
    spec:
      selector:
        matchLabels:
          app: nginx-placement
