---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-namespace
  namespace: default
spec:
  clusterConditions:
  - type: OK
  clusterSelector:
    matchExpressions: []