apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: bma-subscription
  namespace: default
  annotations:
    apps.open-cluster-management.io/github-path: bma/BareMetalAssets
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: baremetal-assets/datacenter01
  placement:
    local: true
